# Generated by Django 3.0.3 on 2020-02-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BateriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.IntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')])),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipoDeComputoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('watts', models.IntegerField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoDiario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoDeDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalConsumoDiario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token', models.UUIDField()),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.EquipoDeComputoModel')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoPanelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsp', models.DecimalField(decimal_places=2, default=3.18, max_digits=10)),
                ('potenciaDePanel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolerancia', models.DecimalField(decimal_places=2, default=1.3, max_digits=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.ReporteModel')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoBateriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrienteNecesaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autonomiaDias', models.IntegerField()),
                ('constanteDeDescarga', models.DecimalField(decimal_places=2, default=0.7, max_digits=10)),
                ('bateria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.BateriaModel')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.ReporteModel')),
            ],
        ),
    ]
