# Generated by Django 3.0.3 on 2020-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_auto_20200217_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipodecomputomodel',
            name='descripcion',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='calculopanelmodel',
            name='hsp',
            field=models.DecimalField(decimal_places=2, default=3.97, max_digits=10),
        ),
    ]
