# Generated by Django 3.1.1 on 2020-09-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_auto_20200905_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateriamodel',
            name='voltaje',
            field=models.IntegerField(choices=[(0, 'NA'), (12, '12V'), (24, '24V'), (48, '48V')]),
        ),
    ]
