# Generated by Django 3.1.1 on 2020-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_auto_20200915_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateriamodel',
            name='voltaje',
            field=models.IntegerField(choices=[(0, '0v'), (12, '12V'), (24, '24V'), (48, '48V')]),
        ),
    ]
